window.MOAFORM_SURVEYS = [
  {
    id: "life-001",
    title: "요즘 나의 소비 습관은?",
    category: "라이프스타일",
    description: "온라인 쇼핑과 구독 서비스 이용 경험에 관한 간단한 설문이에요.",
    duration: 8,
    reward: "스타벅스 아이스아메리카노 (5명)",
    slots: 120,
    remaining: 34,
    deadline: "D-2",
    privacy: "연령대·소비 경험",
    researcher: "모아리서치",
    surveyUrl: "https://docs.google.com/forms/d/e/1FAIpQLSfm_HHdA645PWMGS9RXm9cn0i0CzyPn1H9Pw01KksyLGBaTXQ/viewform",
    color: "#eef0ff",
    ink: "#425bea"
  },
  {
    id: "it-002",
    title: "AI 서비스를 어떻게 사용하고 있나요?",
    category: "IT·서비스",
    description: "생성형 AI 서비스의 사용 방식과 만족도에 대한 조사입니다.",
    duration: 12,
    reward: "메가커피 아이스아메리카노 (10명)",
    slots: 80,
    remaining: 19,
    deadline: "D-1",
    privacy: "직업군·서비스 경험",
    researcher: "테크인사이트랩",
    surveyUrl: "https://docs.google.com/forms/d/e/1FAIpQLSfm_HHdA645PWMGS9RXm9cn0i0CzyPn1H9Pw01KksyLGBaTXQ/viewform",
    color: "#e4f7ed",
    ink: "#147a4c"
  },
  {
    id: "food-003",
    title: "편의점 신제품 맛 평가",
    category: "식품",
    description: "최근 출시된 간편식 패키지와 구매 의향에 대한 설문이에요.",
    duration: 5,
    reward: "BBQ 황금올리브치킨 (3명)",
    slots: 200,
    remaining: 88,
    deadline: "D-4",
    privacy: "연령대·식품 선호",
    researcher: "데일리푸드",
    surveyUrl: "https://docs.google.com/forms/d/e/1FAIpQLSfm_HHdA645PWMGS9RXm9cn0i0CzyPn1H9Pw01KksyLGBaTXQ/viewform",
    color: "#fff3cc",
    ink: "#9a6a00"
  },
  {
    id: "edu-004",
    title: "온라인 학습 경험을 들려주세요",
    category: "교육",
    description: "강의 플랫폼 선택 기준과 학습 습관을 알아보기 위한 조사입니다.",
    duration: 10,
    reward: "스타벅스 카페라테 (7명)",
    slots: 150,
    remaining: 63,
    deadline: "D-5",
    privacy: "학습 단계·수강 경험",
    researcher: "배움연구소",
    surveyUrl: "https://docs.google.com/forms/d/e/1FAIpQLSfm_HHdA645PWMGS9RXm9cn0i0CzyPn1H9Pw01KksyLGBaTXQ/viewform",
    color: "#ffeae4",
    ink: "#c34d3d"
  },
  {
    id: "life-005",
    title: "나에게 맞는 주거 공간 찾기",
    category: "라이프스타일",
    description: "1인 가구의 주거 선택과 생활 편의시설에 관한 설문이에요.",
    duration: 7,
    reward: "메가커피 아메리카노 (10명)",
    slots: 100,
    remaining: 41,
    deadline: "D-3",
    privacy: "거주 형태·연령대",
    researcher: "어반리빙랩",
    surveyUrl: "https://docs.google.com/forms/d/e/1FAIpQLSfm_HHdA645PWMGS9RXm9cn0i0CzyPn1H9Pw01KksyLGBaTXQ/viewform",
    color: "#e9f4ff",
    ink: "#2471a8"
  },
  {
    id: "it-006",
    title: "더 편한 모바일 결제를 위한 의견",
    category: "IT·서비스",
    description: "간편결제 사용 과정에서 느낀 장점과 불편을 들려주세요.",
    duration: 6,
    reward: "BBQ 황금올리브치킨 (5명)",
    slots: 180,
    remaining: 112,
    deadline: "D-7",
    privacy: "결제 서비스 경험",
    researcher: "UX그로스팀",
    surveyUrl: "https://docs.google.com/forms/d/e/1FAIpQLSfm_HHdA645PWMGS9RXm9cn0i0CzyPn1H9Pw01KksyLGBaTXQ/viewform",
    color: "#f2eaff",
    ink: "#7651b6"
  },
  {
    id: "beauty-007",
    title: "나의 뷰티 쇼핑 기준은?",
    category: "라이프스타일",
    description: "화장품을 고를 때 중요하게 생각하는 기준과 구매 경험에 관한 설문이에요.",
    duration: 7,
    reward: "올리브영 모바일 상품권 1만원권 (5명)",
    slots: 120,
    remaining: 55,
    deadline: "D-6",
    privacy: "연령대·뷰티 구매 경험",
    researcher: "뷰티인사이트",
    surveyUrl: "https://docs.google.com/forms/d/e/1FAIpQLSfm_HHdA645PWMGS9RXm9cn0i0CzyPn1H9Pw01KksyLGBaTXQ/viewform",
    color: "#eef7dd",
    ink: "#4f7224"
  },
  {
    id: "food-008",
    title: "배달앱 이용 경험을 알려주세요",
    category: "식품",
    description: "배달 메뉴를 고르는 기준과 앱 이용 과정에서 느낀 점을 알아봅니다.",
    duration: 6,
    reward: "배달의민족 상품권 1만원권 (3명)",
    slots: 100,
    remaining: 47,
    deadline: "D-4",
    privacy: "연령대·배달앱 이용 경험",
    researcher: "푸드트렌드랩",
    surveyUrl: "https://docs.google.com/forms/d/e/1FAIpQLSfm_HHdA645PWMGS9RXm9cn0i0CzyPn1H9Pw01KksyLGBaTXQ/viewform",
    color: "#e2f8f6",
    ink: "#16847c"
  },
  {
    id: "it-009",
    title: "학습용 AI 도구 사용 조사",
    category: "IT·서비스",
    description: "공부와 자기계발에 AI 도구를 활용하는 방식에 대한 설문입니다.",
    duration: 8,
    reward: "GS25 모바일 상품권 5천원권 (10명)",
    slots: 140,
    remaining: 76,
    deadline: "D-8",
    privacy: "연령대·AI 도구 사용 경험",
    researcher: "에듀테크리서치",
    surveyUrl: "https://docs.google.com/forms/d/e/1FAIpQLSfm_HHdA645PWMGS9RXm9cn0i0CzyPn1H9Pw01KksyLGBaTXQ/viewform",
    color: "#e7f3ff",
    ink: "#1d66aa"
  }
];
